# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               P. O. Hristov
author:              Peter O. Hristov
email:               p.hristov [at] liv (dot) ac (dot) uk
description:         Post Doctoral Reasearch Assistant DATA-CENTRIC.

twitter_username:    PeterHristov5
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

plugins:
  - jekyll-seo-tag
